/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cms.webservice;

/**
 * @author Kiran Kolli
 */
public class App {

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("Done!");
    }
}
